export const CLIENT_EVENTS = {
  LOGIN: 'LOGIN',
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  START_GAME: 'START_GAME',
  PLAY_CARD: 'PLAY_CARD',
  DRAW_CARD: 'DRAW_CARD'
};

export const ROOM_EVENTS = {
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  GAME_STARTED: 'GAME_STARTED',
  GAME_STATE_UPDATED: 'GAME_STATE_UPDATED',
  INVALID_MOVE: 'INVALID_MOVE',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  TURN_CHANGED: 'TURN_CHANGED',
  GAME_FINISHED: 'GAME_FINISHED'
};
